# Generated by Django 2.1.4 on 2019-01-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0002_categary'),
    ]

    operations = [
        migrations.AddField(
            model_name='categary',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Image/'),
        ),
    ]
