# Generated by Django 2.1.4 on 2019-01-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0003_categary_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
