# Generated by Django 2.1.4 on 2019-01-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
        migrations.AlterField(
            model_name='categary',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='subcategary',
            name='categary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj1.Categary'),
        ),
    ]
