# Generated by Django 2.1.4 on 2019-01-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0005_auto_20190111_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Images/brands/')),
            ],
        ),
        migrations.CreateModel(
            name='catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Images/catalog/')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj1.Categary')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Images/catalog/')),
                ('Price', models.IntegerField(max_length=128)),
                ('Size', models.IntegerField(max_length=128)),
                ('Quality', models.CharField(max_length=128)),
                ('Requirement', models.IntegerField(max_length=128)),
                ('Tag', models.CharField(max_length=128)),
                ('offer', models.IntegerField(max_length=128)),
            ],
        ),
    ]
